### ISSUE TITLE
Question: can functions be called normally inside a coroutine?

### ISSUE THREAD

**Issue by dibyendumajumdar** [Keith-Cancel/Bunki#2]
It was not clear from the examples whether inside the coroutine C functions can be called normally rather than via the call api.

**Comment by Keith-Cancel** [comment]
You can call functions normally. Those call functions just let you call a function on the threads stack if need be.  You would only need to use call function if a function you would call would exceed the size of stack you chose for your coroutines. 

I hope that answers that for you.
